# Generated by Django 2.1.7 on 2019-02-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190227_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='role',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='role',
            name='person',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writers',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
